/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAliasModal: typeof import('./src/components/Modals/AddAliasModal.vue')['default']
    AddDomainModal: typeof import('./src/components/Modals/AddDomainModal.vue')['default']
    AddGroupMemberInput: typeof import('./src/components/AddGroupMemberInput.vue')['default']
    AddGroupMembersModal: typeof import('./src/components/Modals/AddGroupMembersModal.vue')['default']
    AddGroupModal: typeof import('./src/components/Modals/AddGroupModal.vue')['default']
    AddMemberModal: typeof import('./src/components/Modals/AddMemberModal.vue')['default']
    AdvancedSettings: typeof import('./src/components/Settings/AdvancedSettings.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppsMenu: typeof import('./src/components/AppsMenu.vue')['default']
    AttachmentCapsule: typeof import('./src/components/AttachmentCapsule.vue')['default']
    AutocompleteControl: typeof import('./src/components/Controls/AutocompleteControl.vue')['default']
    CopyControl: typeof import('./src/components/Controls/CopyControl.vue')['default']
    DashboardLayout: typeof import('./src/components/DashboardLayout.vue')['default']
    DesktopLayout: typeof import('./src/components/DesktopLayout.vue')['default']
    EditAliasModal: typeof import('./src/components/Modals/EditAliasModal.vue')['default']
    EmojiPicker: typeof import('./src/components/EmojiPicker.vue')['default']
    EmptyLayout: typeof import('./src/components/EmptyLayout.vue')['default']
    FrappeLogo: typeof import('./src/components/Icons/FrappeLogo.vue')['default']
    HeaderActions: typeof import('./src/components/HeaderActions.vue')['default']
    HorizontalControl: typeof import('./src/components/Controls/HorizontalControl.vue')['default']
    LinkControl: typeof import('./src/components/Controls/LinkControl.vue')['default']
    LoginLayout: typeof import('./src/components/LoginLayout.vue')['default']
    MailAccountModal: typeof import('./src/components/Modals/MailAccountModal.vue')['default']
    MailAccountSettings: typeof import('./src/components/Settings/MailAccountSettings.vue')['default']
    MailDate: typeof import('./src/components/MailDate.vue')['default']
    MailDetailsPopover: typeof import('./src/components/MailDetailsPopover.vue')['default']
    MailLogo: typeof import('./src/components/Icons/MailLogo.vue')['default']
    MailThread: typeof import('./src/components/MailThread.vue')['default']
    MailThreadPlaceholder: typeof import('./src/components/MailThreadPlaceholder.vue')['default']
    MobileLayout: typeof import('./src/components/MobileLayout.vue')['default']
    MultiselectInputControl: typeof import('./src/components/Controls/MultiselectInputControl.vue')['default']
    NoMails: typeof import('./src/components/Icons/NoMails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMail: typeof import('./src/components/SendMail.vue')['default']
    SendMailMobileLayout: typeof import('./src/components/SendMailMobileLayout.vue')['default']
    SettingsModal: typeof import('./src/components/Modals/SettingsModal.vue')['default']
    SidebarDetail: typeof import('./src/components/SidebarDetail.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    UserSettings: typeof import('./src/components/Settings/UserSettings.vue')['default']
  }
}
